config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations"
  }

  get "search", to: "search#index"

  get "users/auth/email_confirmation", to: "users/omniauth_callbacks#new_auth"
  post "users/auth/email_confirmation", to: "users/omniauth_callbacks#register_auth"
  get "users/auth/confirm", to: "users/omniauth_callbacks#confirm_auth"

  concern :votable do
    post :upvote, on: :member
    post :downvote, on: :member
  end

  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, concerns: [:votable, :commentable] do
    put :subscribe, on: :member
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      put :best, on: :member
    end
  end

  api_version(module: "Api::V1", path: { value: "api/v1" }, defaults: { format: :json }, default: true) do
    resources :profiles, only: :index do
      get :me, on: :collection
    end
    resources :questions do
      resources :answers, shallow: true
    end
  end

  root to: "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, -> { order is_best: :desc, updated_at: :desc }
  has_one :best_answer, -> { where is_best: true }, class_name: 'Answer'
  has_many :attachments, as: :attachable, inverse_of: :attachable
  belongs_to :created_by, foreign_key: :created_by_id, class_name: 'User'
  has_many :question_subscriptions, dependent: :destroy
  has_many :subscribers, through: :question_subscriptions, source: :user

  scope :digest, -> { where("created_at >= ?", (DateTime.now - 1.day)) }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, :created_by, presence: true

  after_create :subscribe_author

  def set_best_answer(answer)
    raise ArgumentError unless answer.question == self

    if best_answer != answer
      transaction do
        best_answer&.unbest!
        answer.best!
      end
    end
  end

  private

  def subscribe_author
    created_by.subscribe self
  end
end

app/controllers/api/v1/questions_controller.rb
module Api
  module V1
    class QuestionsController < ::Api::V1::ApplicationController
      load_and_authorize_resource class: Question

      def index
        respond_with @questions
      end

      def show
        respond_with @question
      end

      def create
        @question.created_by = current_user
        @question.save
        respond_with @question
      end

      private

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ::ApplicationController
  include Voted
  include Commented

  skip_before_action :authenticate_user!, only: %i[show index]

  load_and_authorize_resource

  before_action :set_gon_question, only: :show
  after_action :publish_question, only: :create

  respond_to :html
  respond_to :js, only: :update

  def index
  end

  def new
  end

  def show
    @answer = Answer.new
  end

  def create
    @question.created_by = current_user
    @question.save
    respond_with @question
  end

  def subscribe
    subscribe_method = current_user.subscribed?(@question) ? :unsubscribe : :subscribe
    current_user.send subscribe_method, @question

    render json: { subscribed: current_user.subscribed?(@question) }
  end

  def update
    @question.update question_params
  end

  def destroy
    respond_with @question.destroy
  end

  private

  def set_gon_question
    gon.question = { id: @question.id, answers: @question.answers.pluck(:id) }
  end

  def publish_question
    return unless @question.persisted?

    template = ApplicationController.render partial: 'questions/question-row',
                                            locals: { question: @question }
    ActionCable.server.broadcast 'questions', template
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :source, :_destroy])
  end

  def redirect_path(question)
    question_path question
  end
end

app/views/questions/_form.html.slim
= simple_form_for @question, class: 'question-form' do |f|
  = f.input :title
  = f.input :body
  .attachments-form
    = f.simple_fields_for :attachments do |a|
      = render 'attachment_fields', f: a
    .links = link_to_add_association 'Add attachment', f, :attachments
  = f.button :submit, 'Save'

app/views/questions/_question-row.html.slim
.card.question.question_row
  .card-body
    h5.card-title = link_to question.title, question_path(question)
    p.card-text = question.body
br

app/views/questions/_question.html.slim
.question
  .question__display
    .question__info-frame
      .question__score.vote
        - if votable? question
          = vote_button upvote_question_path(question), question, :upvote
            i.material-icons keyboard_arrow_up
        .vote__score = question.score
        - if votable? question
          = vote_button downvote_question_path(question), question, :downvote
            i.material-icons keyboard_arrow_down
      .question__info
        div
          = subscription_button question
          h2.question__title = question.title
        .question__body = question.body
        .question__attachments = render question.attachments
      .question__comments
        = render '/comments/comments-list', commentable: @question
    .question__controls
      - if question.created_by == current_user
        = link_to edit_question_path(question),
                  class: 'question__control-button',
                  data: { 'toggle-display' => true,
                    'parent' => '.question',
                    'show' => '.question__form',
                    'hide' => '.question__display' }
          i.material-icons edit
          | Edit
        =< link_to question_path(question),
                   method: :delete,
                   class: 'question__control-button',
                   data: { confirm: 'Are you sure want to delete this record?' }
          i.material-icons restore_from_trash
          | Delete

  .question__form
    .question__form-errors
    = simple_form_for question, remote: true do |f|
      = f.input :title
      = f.input :body
      = render 'nested_attachment_form', form: f
      .question__controls
        = button_tag type: :submit, class: 'question__control-button'
          i.material-icons save
          | Save
        =< link_to '#', class: 'question__control-button',
                        data: { 'toggle-display' => true,
                          'parent' => '.question',
                          'show' => '.question__display',
                          'hide' => '.question__form' }
          i.material-icons cancel
          | Cancel

app/views/questions/_question_row.html.slim
.card
  .card-body
    h5.card-title = link_to question.title, question_path(question)
    p.card-text = question.body
br

app/views/questions/comment.js.erb
(function($) {
  <%- params = { commentable: @question } %>
  <%- params[:comment] = @comment unless @comment.valid? %>
  $('.question__comments').html('<%= j render("/comments/comments-list", **params) %>');
})(jQuery);

app/views/questions/index.html.slim
.row
  .col
    h1 Questions
  .col.text-right
    = link_to new_question_path, class: 'btn btn-primary'
      i.material-icons add
      | Create question
hr

.row
  .col
    .questions
      = render partial: "question-row",
               collection: @questions,
               as: :question

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
.row
  .col
    h1
      | Question #
      = @question.id
  .col.text-right
    = link_to new_question_path, class: 'btn btn-primary'
      i.material-icons add
      | Create question

hr.separator

= render @question

hr.separator

h2 Answers
.answers
  = render @question.answers

hr.separator

- if user_signed_in?
  h2 Your answer
  .answer.question-answer
    .answer__form
      .answer__form-errors
      = simple_form_for [@question, @answer], remote: true do |f|
        = f.input :body, label: false
        = render 'nested_attachment_form', form: f
        .answer__controls
          = button_tag type: :submit, class: 'answer__control-button'
            i.material-icons add
            | Answer the question

app/views/questions/update.js.erb
(function($) {
  <%- if @question.errors.present? %>
    let $question = $('<%= j render(@question) %>');
    let $questionForm = $question.find('.question__form');
    $('.question__form').html($questionForm.html());
  <%- else %>
    $('.question').replaceWith('<%= j render(@question) %>');
  <%- end %>
})(jQuery);