config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations"
  }

  get "search", to: "search#index"

  get "users/auth/email_confirmation", to: "users/omniauth_callbacks#new_auth"
  post "users/auth/email_confirmation", to: "users/omniauth_callbacks#register_auth"
  get "users/auth/confirm", to: "users/omniauth_callbacks#confirm_auth"

  concern :votable do
    post :upvote, on: :member
    post :downvote, on: :member
  end

  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, concerns: [:votable, :commentable] do
    put :subscribe, on: :member
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      put :best, on: :member
    end
  end

  api_version(module: "Api::V1", path: { value: "api/v1" }, defaults: { format: :json }, default: true) do
    resources :profiles, only: :index do
      get :me, on: :collection
    end
    resources :questions do
      resources :answers, shallow: true
    end
  end

  root to: "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :created_by, foreign_key: :created_by_id, class_name: 'User'
  has_many :attachments, as: :attachable, inverse_of: :attachable

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  validates :body, :question, :created_by, presence: true

  after_commit :notificate_question_subscribers

  def self.best
    where is_best: true
  end

  def best!
    update_attributes is_best: true
  end

  def unbest!
    update_attributes is_best: false
  end

  def can_be_best_for?(user)
    (not is_best?) and question.created_by == user
  end

  def notificate_question_subscribers
    NotificateQuestionSubscriberJob.perform_later self
  end
end

app/controllers/answers_controller.rb
class AnswersController < ::ApplicationController
  include Voted
  include Commented

  load_and_authorize_resource :question, only: :create
  load_and_authorize_resource

  after_action :publish_answer

  respond_to :js, only: %i[best create destroy update]

  def create
    @answer = @question.answers.build answer_params
    @answer.created_by = current_user
    @answer.save
  end

  def update
    @answer.update answer_params
  end

  def destroy
    @answer.destroy
  end

  def best
    question = @answer.question
    @previous_best_answer = question.best_answer
    question.set_best_answer @answer
  end

  private

  def publish_answer
    return unless @answer.persisted?

    answer_body = @answer.body.truncate 20
    message = { body: answer_body, created_by: current_user.id }
    AnswersChannel.broadcast_to @answer.question, message
  end

  def redirect_path(answer)
    question_path answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :source, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < ::Api::V1::ApplicationController
      load_and_authorize_resource :question, only: %i[index create]
      load_and_authorize_resource :answer, through: :question, only: %i[index create]
      load_and_authorize_resource except: %i[index create]

      def index
        respond_with @answers
      end

      def show
        respond_with @answer
      end

      def create
        @answer.created_by = current_user
        @answer.save
        respond_with @answer
      end

      private

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/views/answers/_answer.html.slim
.answer data-answer-id=answer.id class=('answer_best' if answer.is_best?)
  .answer__display
    .answer__info-frame
      .answer__score.vote class=('vote_unvotable' unless votable?(answer))
        - if votable? answer
          = vote_button upvote_answer_path(answer), answer, :upvote
            i.material-icons keyboard_arrow_up
        .vote__score = answer.score
        - if votable? answer
          = vote_button downvote_answer_path(answer), answer, :downvote
            i.material-icons keyboard_arrow_down
      .answer__info
        .answer__body = answer.body
        .answer__attachments = render answer.attachments
        .answer__comments
          = render '/comments/comments-list', commentable: answer
        .answer__controls
          - if answer.created_by == current_user
            = link_to edit_answer_path(answer),
                      class: 'answer__control-button',
                        data: { 'toggle-display' => true,
                          'parent' => '.answer',
                          'show' => '.answer__form',
                          'hide' => '.answer__display' }
              i.material-icons edit
              | Edit
            =< link_to answer_path(answer),
                        class: 'answer__control-button',
                        method: :delete,
                        remote: true,
                        data: { confirm: 'Are you sure want to delete this record?' }
              i.material-icons restore_from_trash
              | Delete
          - if answer.can_be_best_for? current_user
            =< link_to best_answer_path(answer),
                        class: 'answer__control-button',
                        method: :put,
                        remote: true
              i.material-icons thumb_up
              | Best answer

  .answer__form.answer__form_remote
    .answer__form-errors
    = simple_form_for answer, remote: true do |f|
      = f.input :body
      = render 'nested_attachment_form', form: f
      .answer__controls
        = button_tag type: :submit, class: 'answer__control-button'
          i.material-icons save
          | Save
        =< link_to '#', class: 'answer__control-button',
                        data: { 'toggle-display' => true,
                          'parent' => '.answer',
                          'show' => '.answer__display',
                          'hide' => '.answer__form_remote' }
          i.material-icons cancel
          | Cancel

app/views/answers/best.js.erb
<%- if @previous_best_answer %>
  $('.answer[data-answer-id="<%= @previous_best_answer.id %>"]').remove();
  $('.answers').prepend('<%= j render(@previous_best_answer) %>');
<%- end %>
$('.answer[data-answer-id="<%= @answer.id %>"]').remove();
$('.answers').prepend('<%= j render(@answer) %>');

app/views/answers/comment.js.erb
(function($) {
  <%- params = { commentable: @answer } %>
  <%- params[:comment] = @comment unless @comment.valid? %>
  $('.answer[data-answer-id="<%= @answer.id %>"] .answer__comments').html('<%= j render("/comments/comments-list", **params) %>');
})(jQuery);

app/views/answers/create.js.erb
<%- if @answer.errors.present? %>
  $('.question-answer .answer__form-errors').html('<ul><li><%= j @answer.errors.full_messages.join("<li></li>") %></li></ul>');
<%- else %>
  $('.question-answer .answer__form-errors').html('');
  $('.answers').prepend('<%= j render(@answer) %>');
  $('.question-answer').find("input[type=text], textarea").val("");
<% end %>

app/views/answers/destroy.js.erb
$('.answer[data-answer-id="<%= @answer.id %>"]').fadeOut(function() {
  $(this).remove();
});

app/views/answers/update.js.erb
(function() {
  <%- if @answer.errors.present? %>
    let $answer = $('<%= j render(@answer) %>');
    let $answerForm = $answer.find('.answer__form');
    $('.answer[data-answer-id="<%= @answer.id %>"] .answer__form').html($answerForm.html());
  <%- else %>
    $('.answer[data-answer-id="<%= @answer.id %>"]').replaceWith('<%= j render(@answer) %>');
  <% end %>
})();