config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations"
  }

  get "search", to: "search#index"

  get "users/auth/email_confirmation", to: "users/omniauth_callbacks#new_auth"
  post "users/auth/email_confirmation", to: "users/omniauth_callbacks#register_auth"
  get "users/auth/confirm", to: "users/omniauth_callbacks#confirm_auth"

  concern :votable do
    post :upvote, on: :member
    post :downvote, on: :member
  end

  concern :commentable do
    post :comment, on: :member
  end

  resources :questions, concerns: [:votable, :commentable] do
    put :subscribe, on: :member
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      put :best, on: :member
    end
  end

  api_version(module: "Api::V1", path: { value: "api/v1" }, defaults: { format: :json }, default: true) do
    resources :profiles, only: :index do
      get :me, on: :collection
    end
    resources :questions do
      resources :answers, shallow: true
    end
  end

  root to: "questions#index"
end

app/controllers/api/v1/application_controller.rb
require 'application_responder'

module Api
  module V1
    class ApplicationController < ActionController::API
      self.responder = ApplicationResponder

      respond_to :json
      check_authorization

      before_action :verify_requested_format!
      before_action :doorkeeper_authorize!

      protected

      def current_resource_owner
        @current_resource_owner ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
      end

      alias_method :current_user, :current_resource_owner
    end
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  protect_from_forgery with: :exception
  check_authorization unless: :devise_controller?
  add_flash_types :success, :error

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_gon_user, if: :user_signed_in?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_path, error: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

  protected

  def set_gon_user
    gon.user = current_user.id
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_type(level)
    case level.to_sym
      when :notice then "alert-info"
      when :success then "alert-success"
      when :error then "alert-danger"
      when :alert then "alert-danger"
    end
  end
end

app/views/application/_attachment_fields.html.slim
.attachment-fields.nested-fields
  - if f.object.source.file
    .attachment-fields__title
      i.material-icons attach_file
      = f.object.source.file.filename
  = f.input :source, as: :file, label: 'File'
  = link_to_remove_association "Remove attachment", f

app/views/application/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.navigation
  a.navbar-brand href="#"
    i.material-icons help_outline
    | HelpME
  .collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Questions', questions_path, class: 'nav-link'
    ul.navbar-nav.ml-auto.navigation__signing
      - if current_user
        li.nav-item
          == link_to destroy_user_session_path, class: 'nav-link', method: :delete
            = current_user.name
            i.material-icons exit_to_app
      - else
        li.nav-item
          == link_to new_user_session_path, class: 'nav-link'
            | Log in
            i.material-icons exit_to_app

app/views/application/_nested_attachment_form.html.slim
.attachments-form
  = form.simple_fields_for :attachments do |a|
    = render 'attachment_fields', f: a
  .attachments-form__links = link_to_add_association 'Add attachment', form, :attachments

app/views/application/_notifications.html.slim
- flash.each do |key, value|
  .alert.alert-dismissible.fade.show class=flash_type(key)
    = value
    button.close type="button" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true" &times

app/views/application/_popup-notifications.html.slim
.notification
  .notification__layout
    .notification__message
    button.notification__close type="button"
      | &times

app/views/application/_search.html.slim
.global-search
  = simple_form_for :search, url: search_path,
                    method: :get,
                    enforce_utf8: false,
                    html: { class: 'global-search__form' } do |f|
    .global-search__query = f.input :query, label: false, input_html: { id: :search, value: @query }
    .global-search__category = f.input :category, label: false, as: :select,
                                       collection: SphinxSearch::CATEGORIES, include_blank: true,
                                       selected: @category
    .global-search__submit-layout
      = button_tag type: :submit, name: nil, class: 'global-search__submit' do
        ' Search
        i.material-icons search